ktor:
    application:
        modules:
            - by.bashlikovvv.ApplicationKt.module
    deployment:
        port: 8080
        sslPort: 8443
    security:
        ssl:
            keyStore: keystore.jks
            keyAlias: key0
            keyStorePassword: 888qazwsxedc
            privateKeyPassword: 888qazwsxedc
